name: default

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip:
      - aiohttp
      - pydantic
      - pydantic_settings
      - polars
      - pdfplumber
      - xlsx2csv
      - xlsxwriter
      - openpyxl
      - openai
      - pytesseract
      - paramiko
      - pillow
