name: default

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip:
      - aiohttp
      - pydantic
      - pydantic_settings
      - polars
      - xlsx2csv
      - xlsxwriter
      - openpyxl
      - python-docx
      - paramiko
      - pyyaml
      - pillow
      - openai
